import './images/b1.jpg';
import './images/b2.jpg';
import './images/b3.jpg';
import './images/b4.jpg';
import './images/b5.jpg';
import './images/b6.jpg';
import './images/b7.jpg';
import './images/b8.jpg';
import './images/b9.jpg';
import './images/b10.jpg';
import './images/b11.jpg';
import './images/b12.jpg';
import './images/b13.jpg';
import './images/icon-1.png';
import './images/icon-2.png';
import './images/icon-3.png';
import './images/icon-4.png';
import './images/icon-5.png';
import './images/icon-6.png';
import './images/icon-7.png';
import './images/icon-8.png';
import './images/icon-9.png';
import './images/icon-10.png';
import './images/icon-11.png';
import './images/icon-12.png';
import './images/icon-13.png';
import './images/icon-14.png';
import './images/icon-15.png';
import './images/icon-16.png';
import './images/icon-17.png';
import './images/icon-18.png';
import './images/icon-19.png';
import './images/icon-20.png';
import './images/tabbar-1.png';
import './images/tabbar-2.png';
import './images/tabbar-3.png';
import './images/tabbar-1-active.png';
import './images/tabbar-2-active.png';
import './images/tabbar-3-active.png';
import './images/wait.png';
import './images/star.png';
import './images/star-1.png';
import './images/qrcode.jpg';
import './images/logo.png';
import './images/avatar.png';




